from sqtray.__version__ import version
from sys import version_info

from distutils.core import setup

Application = 'SqueezeWxTray'

setup(name=Application,
 version=version,
 description="VM Image list subscribing tool.",
 long_description="""This application attempts to be the equivalent of a modern Linux package update
manager but for lists of virtual machines signed with x509. It uses a database
back end, and caches available image lists.""",
 author="O M Synge",
 author_email="owen.synge@desy.de",
 license='Apache License (2.0)',
 install_requires=[
 "wx",
 ],
 url = 'https://github.com/hepix-virtualisation/hepixvmilsubscriber',
 packages = ['sqtray'],
 classifiers=[
 'Development Status :: 1 - UnStable',
 'Environment :: GUI',
 'License :: OSI Approved :: Apache Software License',
 'Operating System :: POSIX',
 'Programming Language :: Python',
 ],
 scripts=['squeezetray'],
 data_files=[('/usr/share/doc/%s-%s' % (Application,version),['README.md','LICENSE','logger.conf','ChangeLog']),
            ('/usr/share/pixmaps/%s' % (Application),['icons/media_eject_128x128.png',
                'icons/media_eject_16x16.png', 
                'icons/media_eject_22x22.png', 
                'icons/media_eject_24x24.png', 
                'icons/media_eject_32x32.png', 
                'icons/media_eject_48x48.png', 
                'icons/media_eject_72x72.png', 
                'icons/media_playback_pause_128x128.png', 
                'icons/media_playback_pause_16x16.png', 
                'icons/media_playback_pause_22x22.png', 
                'icons/media_playback_pause_24x24.png', 
                'icons/media_playback_pause_32x32.png', 
                'icons/media_playback_pause_48x48.png', 
                'icons/media_playback_pause_72x72.png', 
                'icons/media_playback_start_128x128.png', 
                'icons/media_playback_start_16x16.png', 
                'icons/media_playback_start_22x22.png', 
                'icons/media_playback_start_24x24.png', 
                'icons/media_playback_start_32x32.png', 
                'icons/media_playback_start_48x48.png', 
                'icons/media_playback_start_72x72.png', 
                'icons/media_playback_stop_128x128.png',
                'icons/media_playback_stop_16x16.png', 
                'icons/media_playback_stop_22x22.png', 
                'icons/media_playback_stop_24x24.png', 
                'icons/media_playback_stop_32x32.png', 
                'icons/media_playback_stop_48x48.png', 
                'icons/media_playback_stop_72x72.png', 
                'icons/media_record_128x128.png', 
                'icons/media_record_16x16.png', 
                'icons/media_record_22x22.png', 
                'icons/media_record_24x24.png', 
                'icons/media_record_32x32.png', 
                'icons/media_record_48x48.png', 
                'icons/media_record_72x72.png', 
                'icons/media_seek_backward_128x128.png', 
                'icons/media_seek_backward_16x16.png', 
                'icons/media_seek_backward_22x22.png', 
                'icons/media_seek_backward_24x24.png', 
                'icons/media_seek_backward_32x32.png', 
                'icons/media_seek_backward_48x48.png', 
                'icons/media_seek_backward_72x72.png', 
                'icons/media_seek_forward_128x128.png', 
                'icons/media_seek_forward_16x16.png',
                'icons/media_seek_forward_22x22.png',
                'icons/media_seek_forward_24x24.png',
                'icons/media_seek_forward_32x32.png',
                'icons/media_seek_forward_48x48.png',
                'icons/media_seek_forward_72x72.png',
                'icons/media_skip_backward_128x128.png',
                'icons/media_skip_backward_16x16.png',
                'icons/media_skip_backward_22x22.png',
                'icons/media_skip_backward_24x24.png',
                'icons/media_skip_backward_32x32.png',
                'icons/media_skip_backward_48x48.png',
                'icons/media_skip_backward_72x72.png',
                'icons/media_skip_forward_128x128.png',
                'icons/media_skip_forward_16x16.png',
                'icons/media_skip_forward_22x22.png',
                'icons/media_skip_forward_24x24.png',
                'icons/media_skip_forward_32x32.png',
                'icons/media_skip_forward_48x48.png',
                'icons/media_skip_forward_72x72.png'])]

 )
