#----------------------------------------------------------------------
# This file was generated by /usr/share/pyshared/wx-2.8-gtk2-unicode/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

trayDefault =PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGOfPtRkwAAACBj"
    "SFJNAAB6JQAAgIMAAPn/AACA6QAAdTAAAOpgAAA6mAAAF2+SX8VGAAAABmJLR0QA/wD/AP+g"
    "vaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAIuklEQVRo3u2aS2wd1RnHf+ecmblv+9qTYJuA"
    "MSnEhEQ0CQ3PApZaqjyoGolNKRuvarWLJpYum24ipG7aWnJYdHG7qVWpYtGqjSoeCwok4dGq"
    "4CSQhOAQQuqA83Cu77Xv+87MOV3MmIYoFJJcQyLxSUcz0lzd8/993/nO981DGGO4nk1+3QKu"
    "1qzFEyFEW/84n3OzwAFg/chYodTO/75w1SxlBMbdnjUDwM4lnGNpAPI5dyDl2MOPbvs5iVR6"
    "Rz7nDlxXAMD4YP9y7HQ/9z74fYDx6wYgn3OHujpS25Yt78NK9XHDikGW9968LZ9zh64LAGDn"
    "mttvx073Iqwkwulm/f2bYYlyoa0A+Zy77Zb+gaFMphMr1YuQDsLuonPZACsHNwzlc+62axoA"
    "GF91+2qkk8TOrEBIG2F3gEqyZuNWWIJcaBtAPucOr7nrnoF4IoWMZVCJ5SAE0s5iZJJYxwru"
    "um/rQD7nDl9zAPmcm43FU+MDtw4inTQq1oWKuwhhIawMqBTIJLd9ewuxeGo8KnLXDgCw47Y7"
    "1medeAfSyaAS3SgnA0KAtEHGQMaRMZfBDZuywI5rBiCfc7OZbM/2NeuGkE4mBIi7CDsNCIwO"
    "0H6LwG9hsLnzvifJdPVsb1cU2hGB8bXfeTRrpIN0OpBOByq+DGklwqvGoL0GQatK4DfxtMVd"
    "DzyRpU0JfVUA+Zy7zu1dOTywaiPK6QhHrAsZyyJUEjCgfYz2CLwa2m+itebmNZtxe1cO53Pu"
    "uqsFEIud3eV0o1H4x93elcMPPfYLkokECAekBdLBii/HSvShnCy1uSkq59+j1Syj4i5WfBkq"
    "3kmwMMVrf/8NhTMnJoDRy+lYL+xGLwsgEr4jk+3ZvuHhH2dXrd8MMo7vt/DqZZAWQiVQjoty"
    "OpFWmur5I1SLx2g1KiFA4gY6urqJWT7oBscOvMD+fc+WysWzzwC7vgzIFQHkc+5wLJ4aX7tx"
    "U3bDI0+ATIBKgIyDjBMEAX6zilBxlJVG2p0I6VCbm6K+ME2zvoCIddHV8y3icRuCJugG6DoE"
    "Dfbv/ROH33qx1GxUR0fGChNtA4jK//jdD24dWLtxC06yOxSukiGEjIMKIbTvoQMfqZIIlUBI"
    "m0Z5hvrCx7SaFeKZPjqXrQC9KL4BQT2CqNOqFTj87+eZfOO5k9Gy2n3FAFH3uHPVnRuG7n5w"
    "C+muFZHoZOT5CGIRRDiAxBgNSIRwQCi8RpF6ZRZp2aQ7ewANxg9FR8LRtfAY1EDXqRQ/ZvKN"
    "5zl2ZHIP8PTIWGHPlwaIbj7Gb1xx87b7H9mE23MrqARGpUClQWWiYyqqsDGQoXiBDIuXESAk"
    "IPGaVbT2ceLJUDwGCEC3IoAaBBUIqtGoIYIa6BqFMx/xz70vMvPJ9O4oIic/F+D3Ty3LAuOu"
    "2z38wHcfpq9/Fdgu2N1gdWOsToRKh94XsbDCCguEHYldjKD4zLnWAVLKSLhZdGEIYXzQHpgQ"
    "xgR1CMoIvwReCfw58Oc5feoD3nx9H4XzhQlg9Ke/Pf9pon96Uw8cuLF/9cBjP/klxPtD4TIR"
    "CVShdyMJQkgMEoEJJS1qE3xGqBAKIUy0rKJrRoRRIoJXcTAaVBfCXvyNH0ZL18Gv0Jc9z+N3"
    "PM5zf3xqeGbm9BBw66UA1s9MH9357O9+tmPoez+gr//OyPtdYHVirDSGONpIjAGtI0dKCx2E"
    "xQqjQVgIoYhlbkI5aRqlUxjdxBgfo32ElOF9gpSgfaSUCGEQwiDxkdJH+GXwF8AvgjfH6en3"
    "2PPyS5TL5V3A0xfmwxfkwGbcngFQyTAHZJLAWAQ+BBqCIMAgwz5HB2jtYQKfjhvvJZbpBwT1"
    "0ofUzh8m8OtgAoRUCKmQykaikVIiJShpsCxQCqQJkzvMgRe+XA78/11o6wW7UJwgAN9r4Xkt"
    "Aq+J7/+vVei86SES3asRQgGSeuk45TNv0yxPY/wGxvgoJ4lSNpYVx7IdLDuGZdtYtoWyBNXS"
    "aSbfeO7KdqGL7TN14J4tOEk3gjD4rRae18D3GvjNKqnla0l0DUbLyAIU9bkpymcnqRUOI61Y"
    "lCYByk5iOwksexHCQesWR9/Zy/521IFLgFxQiZ8EGYsgmvh+Czvdh5O+CVAgbISwMBpqhfeo"
    "FY5QLRxGexVS7iAmaKK9WgQQw46nOHLgFd4/uLf9lfgiiCywI9PVs33DQ09kV63fRBBohJVG"
    "2qmooXNAxBDCwSCpz01RnT1IvXgMEzTBBCS7BrBjHQTNIjMfn+Dw/peWvhe6BMi427ty+JEf"
    "PUV2+S2ReDv0vpVGWJ0IEaNROk713H4a88cx2gcT7v/GWcZb+/5C4cyHE3xV3eglQNa5vSsP"
    "/HD412htosJmIe1OVKwHaWepl6aonZukVTkVbrMmQArJa6/+jeLsqfUjY4WDlztv2x7ujowV"
    "DhbOnJj48NAr6EYxGnMEjVmMXwsdowOE9lDSCoeymPnkI4qzpyauRPzF1o5bytGDb/61hG4S"
    "NIsEzTmC+nm0XyGsyBqBj1IKZSksK8b7h94sAaNtmPvqAUbGCqVy8ewzh956kaBRDEe9gG4t"
    "gNEI00KKAKUkSkmOHnqdykLhmXa9M2jXY5Vd77+zr+Q1KwSNefzGLEGjSNjXeAgRIJVE64Dj"
    "RydLwK42zdsegJGxQqnZqI4enzpA0JwnaJTw67MYoxG6hhIGJeGDo2/TajUua8f5SgAiiIlD"
    "+/edrFdK6Po8QfUsGB+hq1jK0KiVePftV09+UZH62gAiG52aOkTQKuNVZtBeDamrKGl4d3If"
    "tClxlwxgZKyw++R/TuyZn5/Dq54B7SGpUJo7zfGpd/d8Xm9zzQBE9vSRqWN4lXPoVgmpy/zr"
    "9Zfgoj7+mgUYGSvsKS5UdhcKs3jzxzl9aorTn0zvvrglvmYBIhudmp7FK02x5+V/wBKs/U/N"
    "GMNSfG6Qz7l/+POvVpt8zm37W5lFzcaYJX3RPTpXOneSJVr7iya++djjG4Crs/8CCMpdRNox"
    "qScAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTQtMDgtMTNUMTA6Mjg6MjUrMDI6MDDtt1bpAAAA"
    "JXRFWHRkYXRlOm1vZGlmeQAyMDE0LTA4LTEzVDEwOjI4OjI1KzAyOjAwnOruVQAAAABJRU5E"
    "rkJggg==")
gettrayDefaultData = trayDefault.GetData
gettrayDefaultImage = trayDefault.GetImage
gettrayDefaultBitmap = trayDefault.GetBitmap

